
name: CI

on:
  pull_request:
    branches:
      - master  
  push:    
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn tsc -p src/tsconfig.json
      - run: yarn lint